# Generated by Django 4.2.7 on 2023-12-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactions_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('sender_bank', models.CharField(max_length=255)),
                ('receiver_bank', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('data_ts', models.DateTimeField()),
                ('xtra', models.CharField(default='NA', max_length=255)),
            ],
        ),
    ]
