# Generated by Django 4.2.7 on 2023-12-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('Time_stamp', models.DateTimeField()),
                ('grp_start', models.DateField()),
                ('grp_end', models.DateField()),
                ('grp_name', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('entry_type', models.CharField(max_length=255)),
            ],
        ),
    ]
