# Generated by Django 5.0.4 on 2024-04-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holder', models.CharField(default='NA', max_length=200)),
                ('full_name', models.CharField(default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doc_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('subtype', models.CharField(default='NA', max_length=200)),
                ('cat2', models.CharField(default='NA', max_length=200)),
            ],
        ),
    ]
