# Generated by Django 5.0.4 on 2024-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0003_home_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_menu',
            name='app_icon',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
