# Generated by Django 5.0.4 on 2024-07-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0004_alter_home_menu_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_menu',
            name='app_icon',
            field=models.CharField(max_length=255),
        ),
    ]
