# Generated by Django 4.0.8 on 2024-11-06 18:08

import datetime
from django.db import migrations, models
# from django.utils.timezone import utc
from datetime import datetime, timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0005_alter_home_menu_app_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='docma_firebase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('holder', models.CharField(max_length=200)),
                ('refnumber', models.CharField(max_length=200)),
                ('document_path', models.CharField(max_length=200)),
                ('document_list', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('start_date', models.DateField(verbose_name=datetime(2024, 11, 6, 18, 8, 41, 593351, tzinfo=timezone.utc))),
                ('end_date', models.DateField(verbose_name=datetime(2024, 11, 6, 18, 8, 41, 593351, tzinfo=timezone.utc))),
                ('time_stamp', models.DateTimeField()),
                ('remarks', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('doc_group', models.CharField(default='NA', max_length=200)),
            ],
        ),
    ]
