# Generated by Django 4.0.8 on 2025-06-07 07:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0006_docma_firebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docma_firebase',
            name='end_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 6, 7, 7, 36, 44, 190561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docma_firebase',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 6, 7, 7, 36, 44, 190561, tzinfo=utc)),
        ),
    ]
