# Generated by Django 5.2.1 on 2025-06-07 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DOCMA", "0007_alter_docma_firebase_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docma_firebase",
            name="end_date",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2025, 6, 7, 8, 47, 55, 560025, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="docma_firebase",
            name="start_date",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2025, 6, 7, 8, 47, 55, 559999, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
