# Generated by Django 4.0.8 on 2025-06-22 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0008_alter_docma_firebase_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docma_firebase',
            name='end_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 6, 22, 3, 15, 44, 868096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='docma_firebase',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 6, 22, 3, 15, 44, 868096, tzinfo=utc)),
        ),
    ]
