# Generated by Django 5.2.4 on 2025-07-19 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOCMA', '0010_alter_docma_firebase_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docma_firebase',
            name='end_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 19, 11, 57, 13, 488104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='docma_firebase',
            name='start_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 7, 19, 11, 57, 13, 488104, tzinfo=datetime.timezone.utc)),
        ),
    ]
