# Generated by Django 5.0.4 on 2024-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='button_params',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('button_name', models.CharField(max_length=200)),
                ('button_type', models.CharField(max_length=200)),
                ('button_icon', models.CharField(max_length=200)),
                ('button_url1', models.CharField(max_length=200)),
                ('button_url2', models.CharField(max_length=200)),
                ('button_groupname', models.CharField(max_length=200)),
                ('button_devicename', models.CharField(max_length=200)),
                ('button_parameters', models.CharField(max_length=200)),
                ('button_remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
