# Generated by Django 5.0.4 on 2024-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HOMEAUTOM', '0002_delete_button_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='button_params',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('button_name', models.CharField(max_length=200)),
                ('button_type', models.CharField(max_length=200)),
                ('button_icon', models.CharField(default='NA', max_length=200)),
                ('button_url_on', models.CharField(max_length=400)),
                ('button_url_off', models.CharField(default='NA', max_length=400)),
                ('button_groupname', models.CharField(max_length=200)),
                ('button_parameters', models.CharField(default='NA', max_length=200)),
                ('button_remarks', models.CharField(default='NA', max_length=200)),
            ],
        ),
    ]
