# Generated by Django 4.2.7 on 2024-06-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medtrac_log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('participant', models.CharField(max_length=200)),
                ('recorder', models.CharField(max_length=200)),
                ('test_parameter', models.CharField(max_length=200)),
                ('v1', models.CharField(max_length=200)),
                ('v2', models.CharField(max_length=200)),
                ('v3', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time_stamp', models.DateTimeField()),
                ('remarks', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
            ],
        ),
    ]
