# Generated by Django 4.0.8 on 2025-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0002_food_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='config_discomfort',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discomfort_id', models.CharField(max_length=200)),
                ('discomfort', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HealthIncidentLogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('discomfort', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=200)),
                ('apprx_start_time', models.DateTimeField()),
                ('apprx_end_time', models.DateTimeField()),
                ('medication', models.CharField(max_length=200)),
                ('while_remarks', models.TextField()),
                ('after_remarks', models.TextField()),
                ('time_stamp', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=200)),
            ],
        ),
    ]
