# Generated by Django 4.0.8 on 2025-06-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MEDTRAC', '0003_config_discomfort_healthincidentlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDataLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200, verbose_name='User Name')),
                ('food_qty', models.CharField(max_length=200, verbose_name='Quantity')),
                ('food_description', models.TextField(blank=True, verbose_name='Description')),
                ('food_type', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian'), ('Egg', 'Egg'), ('other', 'Other')], max_length=20)),
                ('food_category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], max_length=20)),
                ('spare', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('time_stamp', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=200, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Meal Data Log',
                'verbose_name_plural': 'Meal Data Logs',
                'ordering': ['-date', '-time_stamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mealdatalog',
            index=models.Index(fields=['user'], name='MEDTRAC_mea_user_e4c9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='mealdatalog',
            index=models.Index(fields=['date'], name='MEDTRAC_mea_date_95ff1a_idx'),
        ),
        migrations.AddIndex(
            model_name='mealdatalog',
            index=models.Index(fields=['food_type'], name='MEDTRAC_mea_food_ty_e79d27_idx'),
        ),
    ]
