# Generated by Django 5.1.1 on 2024-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('temp_location', models.CharField(default='False', max_length=255)),
                ('user_permission', models.CharField(default='all', max_length=255)),
            ],
        ),
    ]
