# Generated by Django 5.1.1 on 2024-10-01 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENERAL_APPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations_data',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locations_data',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
