# Generated by Django 5.1.1 on 2024-10-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENERAL_APPS', '0002_locations_data_group_locations_data_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations_data',
            name='Active',
            field=models.CharField(default='True', max_length=255),
        ),
    ]
