# Generated by Django 5.1.1 on 2024-10-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GENERAL_APPS', '0003_locations_data_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations_data',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
